# Generated by Django 4.2.2 on 2023-06-20 16:32

import apps.forum.models.custom_user
import apps.forum.models.reaction
import apps.forum.models.school
import apps.forum.models.section
import apps.forum.models.status
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('X', 'Deleted')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=models.SET(apps.forum.models.custom_user.CustomUser.get_deleted_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('X', 'Deleted')], default='A', max_length=1)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('X', 'Deleted')], default='A', max_length=1)),
                ('description', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('X', 'Deleted')], default='A', max_length=1)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('X', 'Deleted')], default='A', max_length=1)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('X', 'Deleted')], default='A', max_length=1)),
                ('description', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('X', 'Deleted')], default='A', max_length=1)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('X', 'Deleted')], default='A', max_length=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.postbase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-post'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('X', 'Deleted')], default='A', max_length=1)),
                ('information', models.TextField(max_length=1024)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.postbase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-post'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('X', 'Deleted')], default='A', max_length=1)),
                ('biography', models.CharField(blank=True, max_length=255)),
                ('img', models.ImageField(default='default.jpg', upload_to='profiles')),
                ('is_featured', models.BooleanField(default=False)),
                ('semester', models.CharField(default='not defined', max_length=32)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('current_school', models.ForeignKey(on_delete=models.SET(apps.forum.models.school.School.get_default_school), to='forum.school')),
                ('status', models.ForeignKey(default=apps.forum.models.status.Status.get_default_status, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.status')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReactPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('X', 'Deleted')], default='A', max_length=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.postbase')),
                ('post_reaction', models.ForeignKey(on_delete=models.SET(apps.forum.models.reaction.Reaction.get_default_reaction), to='forum.reaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-post'],
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forum.postbase')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True, max_length=255)),
                ('img', models.ImageField(upload_to='posts')),
                ('file', models.FileField(upload_to='posts')),
                ('rate', models.BigIntegerField(default=0)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('post_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.posttype')),
                ('section', models.ForeignKey(default=apps.forum.models.section.Section.get_default_section, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.section')),
                ('tags', models.ManyToManyField(blank=True, to='forum.tag')),
            ],
            options={
                'ordering': ['-rate'],
            },
            bases=('forum.postbase', models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('postbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forum.postbase')),
                ('content', models.TextField(max_length=255)),
                ('rate', models.BigIntegerField(default=0)),
                ('posted_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_on_%(class)s', to='forum.postbase')),
            ],
            options={
                'ordering': ['-rate'],
            },
            bases=('forum.postbase', models.Model),
        ),
    ]
