# Generated by Django 4.2.2 on 2023-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
