# Generated by Django 4.2.2 on 2023-06-20 17:03

import apps.forum.models.post
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_customuser_slug_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(default=apps.forum.models.post.PostType.get_default_type, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.posttype'),
        ),
    ]
